name: listhook-nextjs
region: nyc

services:
  - name: web
    github:
      repo: granteagon/listhook-nextjs
      branch: main
      deploy_on_push: true

    build_command: npm ci && npm run build
    run_command: npm start

    environment_slug: node-js

    instance_count: 1
    instance_size_slug: basic-xxs

    http_port: 3000

    health_check:
      http_path: /
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CONTACT_EMAIL_TO
        value: support@listhook.com
        scope: RUN_TIME
